# Generated by Django 5.1.9 on 2026-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_cloudinary_storage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulewindow',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Everyday')]),
        ),
    ]
