# Generated by Django 5.1.9 on 2026-04-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_schedulewindow_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='bot_is_active',
            field=models.BooleanField(default=True, help_text='Global switch to pause/resume all bot activities.'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
