# Generated by Django 5.1.9 on 2026-04-13 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post_sent', 'Post Sent'), ('post_failed', 'Post Failed'), ('post_queued', 'Post Queued'), ('schedule_updated', 'Schedule Updated'), ('caption_generated', 'AI Caption Generated'), ('channel_added', 'Channel Added'), ('bot_started', 'Bot Started'), ('bot_stopped', 'Bot Stopped')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramchannel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('reactions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='bot.post')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('posts_sent', models.IntegerField(default=0)),
                ('posts_failed', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_reactions', models.IntegerField(default=0)),
                ('member_count', models.IntegerField(default=0)),
                ('member_growth', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bot.telegramchannel')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('channel', 'date')},
            },
        ),
    ]
